/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Services.ChiTietSPService;
import Services.DongSPService;
import Services.IQLChiTietSPService;
import Services.IQLDongSPService;
import Services.IQLMauSacService;
import Services.IQLNSXService;
import Services.IQLSanPhamService;
import Services.MauSacService;
import Services.NSXService;
import Services.SanPhamService;
import ViewModels.QLCheck;
import ViewModels.QLChiTietSP;
import ViewModels.QLDongSP;
import ViewModels.QLMauSac;
import ViewModels.QLNSX;
import ViewModels.QLSanPham;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author congh
 */
public class jdlSanPham extends javax.swing.JDialog {

    /**
     * Creates new form jdlSanPham
     */
    private List<QLChiTietSP> listQLCT = new ArrayList<>();
    private IQLDongSPService iqldsp = new DongSPService();
    private IQLNSXService iqlnsx = new NSXService();
    private IQLMauSacService iqlmss = new MauSacService();
    private IQLSanPhamService iqlsps = new SanPhamService();
    private IQLChiTietSPService iqlctsps = new ChiTietSPService();
    private DefaultComboBoxModel dcbmnam = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmdsp = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmnnsx = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmmausac = new DefaultComboBoxModel();
    private List<QLDongSP> listdsp = new ArrayList<>();
    private List<QLMauSac> listms = new ArrayList<>();
    private List<QLNSX> listnsx = new ArrayList<>();
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<QLSanPham> listsp = new ArrayList<>();
    private String s = "";

    public jdlSanPham(java.awt.Frame parent, boolean modal, QLCheck qlc) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        tbSanPham.setModel(dtm);
        String[] form = {"id", "IDSP", "IDNSX", "IDMAUSAC", "IDDONGSP", "NamBH", "Mo Ta", "So Luong Ton", "Gia Nhap", "GiaBan"};
        dtm.setColumnIdentifiers(form);
        loadData();
        cbb();
        s = qlc.getSo1();
    }

    private void cbb() {
        cbbMS.setModel(dcbmmausac);
        cbbNamBH.setModel(dcbmnam);
        cbbnsx.setModel(dcbmnnsx);
        cbbdongsp.setModel(dcbmdsp);
        List<String> lists = new ArrayList<>();
        List<String> listsdspcb = new ArrayList<>();
        List<String> listsmscb = new ArrayList<>();
        List<String> listsnsxcb = new ArrayList<>();
        dcbmdsp.removeAllElements();
        dcbmmausac.removeAllElements();
        dcbmnam.removeAllElements();
        dcbmnnsx.removeAllElements();
        for (int i = 2017; i < 2023; i++) {
            lists.add(String.valueOf(i));
        }
        dcbmnam.addAll(lists);
        listdsp = iqldsp.getall();
        for (QLDongSP qLDongSP : listdsp) {
            listsdspcb.add(qLDongSP.getTen());
        }
        dcbmdsp.addAll(listsdspcb);
        cbbdongsp.setSelectedIndex(0);
        listms = iqlmss.getall();
        for (QLMauSac listm : listms) {
            listsmscb.add(listm.getTen());
        }
        dcbmmausac.addAll(listsmscb);
        cbbMS.setSelectedIndex(0);
        listnsx = iqlnsx.getALL();
        for (QLNSX qlnsx : listnsx) {
            listsnsxcb.add(qlnsx.getTen());
        }
        dcbmnnsx.addAll(listsnsxcb);
        cbbnsx.setSelectedIndex(0);
        cbbNamBH.setSelectedIndex(0);
    }

    private void inPut(List<QLChiTietSP> listQLCT) {
        dtm.setRowCount(0);
        for (QLChiTietSP qLChiTietSP : listQLCT) {
            dtm.addRow(qLChiTietSP.torow());
        }
    }

    private void loadData() {
        listsp = iqlsps.getall();
        listQLCT = iqlctsps.GetAll();
        inPut(listQLCT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSoLuong = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        bttThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttSua = new javax.swing.JButton();
        cbbNamBH = new javax.swing.JComboBox<>();
        bttXoa = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        cbbdongsp = new javax.swing.JComboBox<>();
        cbbMS = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbnsx = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Mã SP");

        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Mô tả");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tên SP");

        bttThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttThem.setText("Thêm");
        bttThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Năm bảo hành");

        bttSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttSua.setText("Sửa");
        bttSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSuaActionPerformed(evt);
            }
        });

        cbbNamBH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbbNamBH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022" }));

        bttXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttXoa.setText("Xóa");
        bttXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttXoaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Số lượng");

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Gía nhập");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Gía bán");

        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTim.setText("Tim");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        cbbdongsp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbbdongsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbMS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbbMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Dòng sản phẩm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Màu sắc");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NSX");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        cbbnsx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbbnsx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbnsx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbnsxMouseClicked(evt);
            }
        });

        jLabel6.setText("NHập mã sản phẩm");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(48, 48, 48)
                                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(47, 47, 47))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenSP)
                                            .addComponent(cbbMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtMoTa)
                                            .addComponent(cbbnsx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbbdongsp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(27, 27, 27)))
                .addComponent(btnTim)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttSua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttThem))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbbNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(bttThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttSua)
                        .addGap(13, 13, 13)
                        .addComponent(bttXoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbbnsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbdongsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnTim)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed
private void clear(){
    txtGiaBan.setText("");
    txtGiaNhap.setText("");
    txtMaSP.setText("");
    txtMoTa.setText("");
    txtSoLuong.setText("");
    txtTenSP.setText("");
    txtTimKiem.setText("");
    cbbMS.setSelectedIndex(0);
    cbbNamBH.setSelectedIndex(0);
    cbbdongsp.setSelectedIndex(0);
    cbbnsx.setSelectedIndex(0);
}
    private void bttThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThemActionPerformed
        QLChiTietSP chiTietSP = get();
        iqlctsps.save(chiTietSP);
        loadData();
        clear();

    }//GEN-LAST:event_bttThemActionPerformed
    private QLChiTietSP get() {
        QLSanPham qlsp = new QLSanPham(null, txtMaSP.getText(), txtTenSP.getText());
        iqlsps.save(qlsp);
        String idSp = iqlsps.getone(txtMaSP.getText()).getId();
        String idms = iqlmss.finone((String) cbbMS.getSelectedItem()).getId();
        String idnsx = iqlnsx.finone((String) cbbnsx.getSelectedItem()).getId();
        String iddsp = iqldsp.finone((String) cbbdongsp.getSelectedItem()).getId();
        QLSanPham qlsp1 = new QLSanPham(idSp);
        QLMauSac qlms1 = new QLMauSac(idms);
        QLNSX qlnsx1 = new QLNSX(idnsx);
        QLDongSP qldsp1 = new QLDongSP(iddsp);
        double giaNhap = Double.parseDouble(txtGiaNhap.getText().trim());
        double giaBan = Double.parseDouble(txtGiaBan.getText().trim());
        QLChiTietSP qlctsp = new QLChiTietSP(null, qlsp1, qlnsx1, qlms1, qldsp1,
                Integer.parseInt((String) cbbNamBH.getSelectedItem()), txtMaSP.getText(), Integer.parseInt(txtSoLuong.getText()),
                BigDecimal.valueOf(giaNhap),
                BigDecimal.valueOf(giaBan));
        return qlctsp;
    }
    private QLChiTietSP getsua() {
        int i = tbSanPham.getSelectedRow();
        QLSanPham qlsp2 = listsp.get(i);
        QLSanPham qlsp = new QLSanPham(qlsp2.getId(), txtMaSP.getText(), txtTenSP.getText());
        System.out.println(qlsp2.getId());
        iqlsps.update(qlsp);
        String idSp = iqlsps.getone(txtMaSP.getText()).getId();
        String idms = iqlmss.finone((String) cbbMS.getSelectedItem()).getId();
        String idnsx = iqlnsx.finone((String) cbbnsx.getSelectedItem()).getId();
        String iddsp = iqldsp.finone((String) cbbdongsp.getSelectedItem()).getId();
        QLSanPham qlsp1 = new QLSanPham(idSp);
        QLMauSac qlms1 = new QLMauSac(idms);
        QLNSX qlnsx1 = new QLNSX(idnsx);
        QLDongSP qldsp1 = new QLDongSP(iddsp);
        double giaNhap = Double.parseDouble(txtGiaNhap.getText().trim());
        double giaBan = Double.parseDouble(txtGiaBan.getText().trim());
        String id = "";
        for (QLChiTietSP qLChiTietSP : listQLCT) {
            if (qLChiTietSP.getIdSp().getId().equals(qldsp1.getId())) {
                id = qLChiTietSP.getId();
            }
        }
        QLChiTietSP qlctsp = new QLChiTietSP(id, qlsp1, qlnsx1, qlms1, qldsp1,
                Integer.parseInt((String) cbbNamBH.getSelectedItem()), txtMaSP.getText(), Integer.parseInt(txtSoLuong.getText()),
                BigDecimal.valueOf(giaNhap),
                BigDecimal.valueOf(giaBan));
        return qlctsp;
    }
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        QLSanPham qlsp1 = iqlsps.getone(txtTimKiem.getText());
        System.out.println(qlsp1.getId());
        String id = "";
        for (QLChiTietSP qLChiTietSP : listQLCT) {
            if (qLChiTietSP.getIdSp().getId().equals(qlsp1.getId())) {
                id = qLChiTietSP.getId();
            }
        }
        QLChiTietSP qlct1 = new QLChiTietSP(id);
        QLChiTietSP qlct = iqlctsps.getone(qlct1);
        for (QLSanPham qlsp : listsp) {
            if (qlsp.getId().equals(qlct.getIdSp().getId())) {
                txtMaSP.setText(qlsp.getMa());
                txtTenSP.setText(qlsp.getTen());
            }
        }
        for (QLDongSP qldsp : listdsp) {
            if (qldsp.getId().equals(qlct.getIdDongSP().getId())) {
                cbbdongsp.setSelectedItem(qldsp.getTen());
            }
        }
        for (QLMauSac qlms : listms) {
            if (qlms.getId().equals(qlct.getIdMauSac().getId())) {
                cbbMS.setSelectedItem(qlms.getTen());
            }
        }
        for (QLNSX qlnsx : listnsx) {
            if (qlnsx.getId().equals(qlct.getIdNSX().getId())) {
                cbbnsx.setSelectedItem(qlnsx.getTen());
            }
        }
        cbbNamBH.setSelectedItem(String.valueOf(qlct.getNamBH()));
        txtGiaNhap.setText(String.valueOf(qlct.getGiaNhap()));
        txtGiaBan.setText(String.valueOf(qlct.getGiaBan()));
        txtSoLuong.setText(String.valueOf(qlct.getSoLuongTon()));
        txtMoTa.setText(qlct.getMoTa());
    }//GEN-LAST:event_btnTimActionPerformed
    private void filldata(int i) {
        QLChiTietSP qlct = listQLCT.get(i);
        for (QLSanPham qlsp : listsp) {
            if (qlsp.getId().equals(qlct.getIdSp().getId())) {
                txtMaSP.setText(qlsp.getMa());
                txtTenSP.setText(qlsp.getTen());
            }
        }
        for (QLDongSP qldsp : listdsp) {
            if (qldsp.getId().equals(qlct.getIdDongSP().getId())) {
                cbbdongsp.setSelectedItem(qldsp.getTen());
            }
        }
        for (QLMauSac qlms : listms) {
            if (qlms.getId().equals(qlct.getIdMauSac().getId())) {
                cbbMS.setSelectedItem(qlms.getTen());
            }
        }
        for (QLNSX qlnsx : listnsx) {
            if (qlnsx.getId().equals(qlct.getIdNSX().getId())) {
                cbbnsx.setSelectedItem(qlnsx.getTen());
            }
        }
        cbbNamBH.setSelectedItem(String.valueOf(qlct.getNamBH()));
        txtGiaNhap.setText(String.valueOf(qlct.getGiaNhap()));
        txtGiaBan.setText(String.valueOf(qlct.getGiaBan()));
        txtSoLuong.setText(String.valueOf(qlct.getSoLuongTon()));
        txtMoTa.setText(qlct.getMoTa());
    }
    private void bttXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttXoaActionPerformed
        // TODO add your handling code here:
        int i = tbSanPham.getSelectedRow();
        QLChiTietSP qlct = listQLCT.get(i);
        QLSanPham QLSP = listsp.get(i);
        if (iqlctsps.remove(qlct.getId()) == 1 && iqlsps.remove(QLSP.getId()) == true) {
            JOptionPane.showMessageDialog(this, "Remove Complete");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Remove Faild");
        }
    }//GEN-LAST:event_bttXoaActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
        int i = tbSanPham.getSelectedRow();
        filldata(i);
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        QLCheck qlc = new QLCheck(s);
        new MainScreen(qlc).setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbnsxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbnsxMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbbnsxMouseClicked

    private void bttSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSuaActionPerformed
        // TODO add your handling code here:
        QLChiTietSP qlctsp = getsua();
        iqlctsps.update(qlctsp);
        loadData();
    }//GEN-LAST:event_bttSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            QLCheck qlc = new QLCheck();
            jdlSanPham dialog = new jdlSanPham(new javax.swing.JFrame(), true, qlc);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JButton bttSua;
    private javax.swing.JButton bttThem;
    private javax.swing.JButton bttXoa;
    private javax.swing.JComboBox<String> cbbMS;
    private javax.swing.JComboBox<String> cbbNamBH;
    private javax.swing.JComboBox<String> cbbdongsp;
    private javax.swing.JComboBox<String> cbbnsx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
